FROM "nexcer/flutter-web"

# install all needed stuff
RUN apt-get update
RUN apt-get install -y curl git unzip npm cmake ninja-build clang-tools clang pkg-config libvlccore-dev libvlc-dev gtk+-3.0 glib-2.0 gio-2.0